const i18n = {
    // English
    'en': {
        langName: 'English', title: 'Quick Invoice Pro', clientDetails: 'Client Details', companyName: 'Company Name', clientNamePlaceholder: 'Client Inc.', address: 'Address', addressPlaceholder: '123 Main Street...', yourDetails: 'Your Details', yourCompanyNamePlaceholder: 'Your Company LLC', yourAddressPlaceholder: '456 Your Street...', invoiceDetails: 'Invoice Details', invoiceNumber: 'Invoice Number', issueDate: 'Issue Date', dueDate: 'Due Date', currency: 'Currency', invoiceItems: 'Invoice Items', description: 'Description', qty: 'Qty', price: 'Price', addItem: '+ Add Item', totalsAndNotes: 'Totals & Notes', discount: 'Discount', discountPlaceholder: '10% or 50', taxRate: 'Tax Rate (%)', paymentLink: 'Payment Link', paymentLinkPlaceholder: 'https://provider.com/pay', notes: 'Notes', notesPlaceholder: 'Thank you for your business!', downloadPDF: 'Download PDF', print: 'Print', reset: 'Reset', from: 'From', to: 'To', subtotal: 'Subtotal', tax: 'Tax', total: 'Total', payNow: 'Pay Now', pdfBillTo: 'BILL TO', pdfDateIssued: 'DATE ISSUED', pdfDueDate: 'DUE DATE', pdfInvoice: 'INVOICE', pdfDescription: 'Description', pdfQuantity: 'Quantity', pdfUnitPrice: 'Unit Price', pdfAmount: 'Amount', pdfSubtotal: 'Subtotal', pdfDiscount: 'Discount', pdfTax: 'Tax', pdfTotal: 'Total', pdfNotes: 'Notes', pdfPayOnline: 'Pay Online',
    },
    // Spanish
    'es': {
        langName: 'Español', title: 'Factura Rápida Pro', clientDetails: 'Detalles del Cliente', companyName: 'Nombre de la Empresa', clientNamePlaceholder: 'Cliente Inc.', address: 'Dirección', addressPlaceholder: 'Calle Principal 123...', yourDetails: 'Tus Detalles', yourCompanyNamePlaceholder: 'Tu Empresa SL', yourAddressPlaceholder: 'Tu Calle 456...', invoiceDetails: 'Detalles de la Factura', invoiceNumber: 'Número de Factura', issueDate: 'Fecha de Emisión', dueDate: 'Fecha de Vencimiento', currency: 'Moneda', invoiceItems: 'Artículos de la Factura', description: 'Descripción', qty: 'Cant.', price: 'Precio', addItem: '+ Añadir Artículo', totalsAndNotes: 'Totales y Notas', discount: 'Descuento', discountPlaceholder: '10% o 50', taxRate: 'Tasa de Impuestos (%)', paymentLink: 'Enlace de Pago', paymentLinkPlaceholder: 'https://proveedor.com/pagar', notes: 'Notas', notesPlaceholder: '¡Gracias por su compra!', downloadPDF: 'Descargar PDF', print: 'Imprimir', reset: 'Reiniciar', from: 'De', to: 'Para', subtotal: 'Subtotal', tax: 'Impuestos', total: 'Total', payNow: 'Pagar Ahora', pdfBillTo: 'FACTURAR A', pdfDateIssued: 'FECHA DE EMISIÓN', pdfDueDate: 'FECHA DE VENCIMIENTO', pdfInvoice: 'FACTURA', pdfDescription: 'Descripción', pdfQuantity: 'Cantidad', pdfUnitPrice: 'Precio Unitario', pdfAmount: 'Importe', pdfSubtotal: 'Subtotal', pdfDiscount: 'Descuento', pdfTax: 'Impuestos', pdfTotal: 'Total', pdfNotes: 'Notas', pdfPayOnline: 'Pagar Online',
    },
    // French
    'fr': {
        langName: 'Français', title: 'Facture Rapide Pro', clientDetails: 'Détails du Client', companyName: 'Nom de l\'entreprise', clientNamePlaceholder: 'Client Inc.', address: 'Adresse', addressPlaceholder: '123 Rue Principale...', yourDetails: 'Vos Coordonnées', yourCompanyNamePlaceholder: 'Votre Entreprise SARL', yourAddressPlaceholder: '456 Votre Rue...', invoiceDetails: 'Détails de la Facture', invoiceNumber: 'Numéro de Facture', issueDate: 'Date d\'émission', dueDate: 'Date d\'échéance', currency: 'Devise', invoiceItems: 'Éléments de la Facture', description: 'Description', qty: 'Qté', price: 'Prix', addItem: '+ Ajouter un article', totalsAndNotes: 'Totaux et Notes', discount: 'Remise', discountPlaceholder: '10% ou 50', taxRate: 'Taux de TVA (%)', paymentLink: 'Lien de paiement', paymentLinkPlaceholder: 'https://fournisseur.com/payer', notes: 'Notes', notesPlaceholder: 'Merci pour votre confiance!', downloadPDF: 'Télécharger le PDF', print: 'Imprimer', reset: 'Réinitialiser', from: 'De', to: 'À', subtotal: 'Sous-total', tax: 'Taxe', total: 'Total', payNow: 'Payer Maintenant', pdfBillTo: 'FACTURER À', pdfDateIssued: 'DATE D\'ÉMISSION', pdfDueDate: 'DATE D\'ÉCHÉANCE', pdfInvoice: 'FACTURE', pdfDescription: 'Description', pdfQuantity: 'Quantité', pdfUnitPrice: 'Prix Unitaire', pdfAmount: 'Montant', pdfSubtotal: 'Sous-total', pdfDiscount: 'Remise', pdfTax: 'Taxe', pdfTotal: 'Total', pdfNotes: 'Notes', pdfPayOnline: 'Payer en ligne',
    },
    // German
    'de': {
        langName: 'Deutsch', title: 'Schnellrechnung Pro', clientDetails: 'Kundendetails', companyName: 'Firmenname', clientNamePlaceholder: 'Kunde GmbH', address: 'Adresse', addressPlaceholder: 'Hauptstraße 123...', yourDetails: 'Ihre Details', yourCompanyNamePlaceholder: 'Ihre Firma GmbH', yourAddressPlaceholder: 'Ihre Straße 456...', invoiceDetails: 'Rechnungsdetails', invoiceNumber: 'Rechnungsnummer', issueDate: 'Ausstellungsdatum', dueDate: 'Fälligkeitsdatum', currency: 'Währung', invoiceItems: 'Rechnungspositionen', description: 'Beschreibung', qty: 'Menge', price: 'Preis', addItem: '+ Position hinzufügen', totalsAndNotes: 'Summen & Notizen', discount: 'Rabatt', discountPlaceholder: '10% oder 50', taxRate: 'Steuersatz (%)', paymentLink: 'Zahlungslink', paymentLinkPlaceholder: 'https://anbieter.com/zahlen', notes: 'Notizen', notesPlaceholder: 'Vielen Dank für Ihren Auftrag!', downloadPDF: 'PDF herunterladen', print: 'Drucken', reset: 'Zurücksetzen', from: 'Von', to: 'An', subtotal: 'Zwischensumme', tax: 'Steuer', total: 'Gesamt', payNow: 'Jetzt bezahlen', pdfBillTo: 'RECHNUNG AN', pdfDateIssued: 'AUSSTELLUNGSDATUM', pdfDueDate: 'FÄLLIGKEITSDATUM', pdfInvoice: 'RECHNUNG', pdfDescription: 'Beschreibung', pdfQuantity: 'Menge', pdfUnitPrice: 'Stückpreis', pdfAmount: 'Betrag', pdfSubtotal: 'Zwischensumme', pdfDiscount: 'Rabatt', pdfTax: 'Steuer', pdfTotal: 'Gesamt', pdfNotes: 'Notizen', pdfPayOnline: 'Online bezahlen',
    },
    // Portuguese
    'pt': {
        langName: 'Português', title: 'Fatura Rápida Pro', clientDetails: 'Detalhes do Cliente', companyName: 'Nome da Empresa', clientNamePlaceholder: 'Cliente Ltda.', address: 'Endereço', addressPlaceholder: 'Rua Principal, 123...', yourDetails: 'Seus Dados', yourCompanyNamePlaceholder: 'Sua Empresa Ltda.', yourAddressPlaceholder: 'Sua Rua, 456...', invoiceDetails: 'Detalhes da Fatura', invoiceNumber: 'Número da Fatura', issueDate: 'Data de Emissão', dueDate: 'Data de Vencimento', currency: 'Moeda', invoiceItems: 'Itens da Fatura', description: 'Descrição', qty: 'Qtd', price: 'Preço', addItem: '+ Adicionar Item', totalsAndNotes: 'Totais e Notas', discount: 'Desconto', discountPlaceholder: '10% ou 50', taxRate: 'Taxa de Imposto (%)', paymentLink: 'Link de Pagamento', paymentLinkPlaceholder: 'https://provedor.com/pagar', notes: 'Notas', notesPlaceholder: 'Obrigado pelo seu negócio!', downloadPDF: 'Baixar PDF', print: 'Imprimir', reset: 'Redefinir', from: 'De', to: 'Para', subtotal: 'Subtotal', tax: 'Imposto', total: 'Total', payNow: 'Pagar Agora', pdfBillTo: 'FATURAR PARA', pdfDateIssued: 'DATA DE EMISSÃO', pdfDueDate: 'DATA DE VENCIMENTO', pdfInvoice: 'FATURA', pdfDescription: 'Descrição', pdfQuantity: 'Quantidade', pdfUnitPrice: 'Preço Unitário', pdfAmount: 'Valor', pdfSubtotal: 'Subtotal', pdfDiscount: 'Desconto', pdfTax: 'Imposto', pdfTotal: 'Total', pdfNotes: 'Notas', pdfPayOnline: 'Pagar Online',
    },
    // Russian
    'ru': {
        langName: 'Русский', title: 'Экспресс-Счёт Pro', clientDetails: 'Данные клиента', companyName: 'Название компании', clientNamePlaceholder: 'Клиент ООО', address: 'Адрес', addressPlaceholder: 'Главная ул., 123...', yourDetails: 'Ваши данные', yourCompanyNamePlaceholder: 'Ваша Компания ООО', yourAddressPlaceholder: 'Ваша ул., 456...', invoiceDetails: 'Детали счёта', invoiceNumber: 'Номер счёта', issueDate: 'Дата выставления', dueDate: 'Срок оплаты', currency: 'Валюта', invoiceItems: 'Позиции счёта', description: 'Описание', qty: 'Кол-во', price: 'Цена', addItem: '+ Добавить позицию', totalsAndNotes: 'Итоги и примечания', discount: 'Скидка', discountPlaceholder: '10% или 50', taxRate: 'Налоговая ставка (%)', paymentLink: 'Ссылка для оплаты', paymentLinkPlaceholder: 'https://provider.com/pay', notes: 'Примечания', notesPlaceholder: 'Спасибо за ваш заказ!', downloadPDF: 'Скачать PDF', print: 'Печать', reset: 'Сбросить', from: 'От', to: 'Кому', subtotal: 'Подытог', tax: 'Налог', total: 'Итого', payNow: 'Оплатить сейчас', pdfBillTo: 'СЧЁТ ДЛЯ', pdfDateIssued: 'ДАТА ВЫСТАВЛЕНИЯ', pdfDueDate: 'СРОК ОПЛАТЫ', pdfInvoice: 'СЧЁТ', pdfDescription: 'Описание', pdfQuantity: 'Количество', pdfUnitPrice: 'Цена за ед.', pdfAmount: 'Сумма', pdfSubtotal: 'Подытог', pdfDiscount: 'Скидка', pdfTax: 'Налог', pdfTotal: 'Итого', pdfNotes: 'Примечания', pdfPayOnline: 'Оплатить онлайн',
    },
    // Slovene
    'sl': {
        langName: 'Slovenščina', title: 'Hitri Račun Pro', clientDetails: 'Podrobnosti o stranki', companyName: 'Ime podjetja', clientNamePlaceholder: 'Stranka d.o.o.', address: 'Naslov', addressPlaceholder: 'Glavna ulica 123...', yourDetails: 'Vaši podatki', yourCompanyNamePlaceholder: 'Vaše podjetje d.o.o.', yourAddressPlaceholder: 'Vaša ulica 456...', invoiceDetails: 'Podrobnosti računa', invoiceNumber: 'Številka računa', issueDate: 'Datum izdaje', dueDate: 'Datum zapadlosti', currency: 'Valuta', invoiceItems: 'Postavke računa', description: 'Opis', qty: 'Količina', price: 'Cena', addItem: '+ Dodaj postavko', totalsAndNotes: 'Vsote in opombe', discount: 'Popust', discountPlaceholder: '10% ali 50', taxRate: 'Davčna stopnja (%)', paymentLink: 'Povezava za plačilo', paymentLinkPlaceholder: 'https://ponudnik.com/placaj', notes: 'Opombe', notesPlaceholder: 'Hvala za vaše poslovanje!', downloadPDF: 'Prenesi PDF', print: 'Natisni', reset: 'Ponastavi', from: 'Od', to: 'Za', subtotal: 'Vmesni znesek', tax: 'Davek', total: 'Skupaj', payNow: 'Plačaj zdaj', pdfBillTo: 'RAČUN ZA', pdfDateIssued: 'DATUM IZDAJE', pdfDueDate: 'DATUM ZAPADLOSTI', pdfInvoice: 'RAČUN', pdfDescription: 'Opis', pdfQuantity: 'Količina', pdfUnitPrice: 'Cena na enoto', pdfAmount: 'Znesek', pdfSubtotal: 'Vmesni znesek', pdfDiscount: 'Popust', pdfTax: 'Davek', pdfTotal: 'Skupaj', pdfNotes: 'Opombe', pdfPayOnline: 'Plačaj na spletu',
    },
    // Croatian
    'hr': {
        langName: 'Hrvatski', title: 'Brza Faktura Pro', clientDetails: 'Detalji klijenta', companyName: 'Naziv tvrtke', clientNamePlaceholder: 'Klijent d.o.o.', address: 'Adresa', addressPlaceholder: 'Glavna ulica 123...', yourDetails: 'Vaši podaci', yourCompanyNamePlaceholder: 'Vaša tvrtka d.o.o.', yourAddressPlaceholder: 'Vaša ulica 456...', invoiceDetails: 'Detalji fakture', invoiceNumber: 'Broj fakture', issueDate: 'Datum izdavanja', dueDate: 'Datum dospijeća', currency: 'Valuta', invoiceItems: 'Stavke fakture', description: 'Opis', qty: 'Količina', price: 'Cijena', addItem: '+ Dodaj stavku', totalsAndNotes: 'Ukupno i bilješke', discount: 'Popust', discountPlaceholder: '10% ili 50', taxRate: 'Porezna stopa (%)', paymentLink: 'Link za plaćanje', paymentLinkPlaceholder: 'https://pruatelj.com/plati', notes: 'Bilješke', notesPlaceholder: 'Hvala na suradnji!', downloadPDF: 'Preuzmi PDF', print: 'Ispis', reset: 'Resetiraj', from: 'Od', to: 'Za', subtotal: 'Međuzbroj', tax: 'Porez', total: 'Ukupno', payNow: 'Plati sada', pdfBillTo: 'RAČUN ZA', pdfDateIssued: 'DATUM IZDAVANJA', pdfDueDate: 'DATUM DOSPIJEĆA', pdfInvoice: 'RAČUN', pdfDescription: 'Opis', pdfQuantity: 'Količina', pdfUnitPrice: 'Jedinična cijena', pdfAmount: 'Iznos', pdfSubtotal: 'Međuzbroj', pdfDiscount: 'Popust', pdfTax: 'Porez', pdfTotal: 'Ukupno', pdfNotes: 'Bilješke', pdfPayOnline: 'Plati online',
    },
    // Hindi
    'hi': {
        langName: 'हिन्दी', title: 'क्विक इनवॉइस प्रो', clientDetails: 'ग्राहक विवरण', companyName: 'कंपनी का नाम', clientNamePlaceholder: 'ग्राहक इंक।', address: 'पता', addressPlaceholder: '123 मुख्य सड़क...', yourDetails: 'आपके विवरण', yourCompanyNamePlaceholder: 'आपकी कंपनी LLC', yourAddressPlaceholder: '456 आपकी सड़क...', invoiceDetails: 'चालान विवरण', invoiceNumber: 'चालान संख्या', issueDate: 'जारी करने की तारीख', dueDate: 'देय तिथि', currency: 'मुद्रा', invoiceItems: 'चालान आइटम', description: 'विवरण', qty: 'मात्रा', price: 'कीमत', addItem: '+ आइटम जोड़ें', totalsAndNotes: 'योग और नोट्स', discount: 'छूट', discountPlaceholder: '10% या 50', taxRate: 'कर दर (%)', paymentLink: 'भुगतान लिंक', paymentLinkPlaceholder: 'https://provider.com/pay', notes: 'टिप्पणियाँ', notesPlaceholder: 'आपके व्यवसाय के लिए धन्यवाद!', downloadPDF: 'पीडीएफ डाउनलोड करें', print: 'प्रिंट', reset: 'रीसेट', from: 'से', to: 'को', subtotal: 'उप-योग', tax: 'कर', total: 'कुल', payNow: 'अभी भुगतान करें', pdfBillTo: 'बिल किसको', pdfDateIssued: 'जारी करने की तारीख', pdfDueDate: 'देय तिथि', pdfInvoice: 'चालान', pdfDescription: 'विवरण', pdfQuantity: 'मात्रा', pdfUnitPrice: 'इकाई मूल्य', pdfAmount: 'राशि', pdfSubtotal: 'उप-योग', pdfDiscount: 'छूट', pdfTax: 'कर', pdfTotal: 'कुल', pdfNotes: 'टिप्पणियाँ', pdfPayOnline: 'ऑनलाइन भुगतान करें',
    },
    // Chinese (Simplified)
    'zh': {
        langName: '中文 (简体)', title: '快速发票 Pro', clientDetails: '客户详情', companyName: '公司名称', clientNamePlaceholder: '客户公司', address: '地址', addressPlaceholder: '主要街道123号...', yourDetails: '您的详情', yourCompanyNamePlaceholder: '您的公司', yourAddressPlaceholder: '您的街道456号...', invoiceDetails: '发票详情', invoiceNumber: '发票号码', issueDate: '开票日期', dueDate: '到期日期', currency: '货币', invoiceItems: '发票项目', description: '描述', qty: '数量', price: '价格', addItem: '+ 添加项目', totalsAndNotes: '总计与备注', discount: '折扣', discountPlaceholder: '10% 或 50', taxRate: '税率 (%)', paymentLink: '付款链接', paymentLinkPlaceholder: 'https://provider.com/pay', notes: '备注', notesPlaceholder: '感谢您的惠顾！', downloadPDF: '下载PDF', print: '打印', reset: '重置', from: '来自', to: '至', subtotal: '小计', tax: '税额', total: '总计', payNow: '立即付款', pdfBillTo: '账单收件人', pdfDateIssued: '开票日期', pdfDueDate: '到期日期', pdfInvoice: '发票', pdfDescription: '描述', pdfQuantity: '数量', pdfUnitPrice: '单价', pdfAmount: '金额', pdfSubtotal: '小计', pdfDiscount: '折扣', pdfTax: '税额', pdfTotal: '总计', pdfNotes: '备注', pdfPayOnline: '在线支付',
    },
    // Japanese
    'ja': {
        langName: '日本語', title: 'クイック請求書 Pro', clientDetails: '顧客詳細', companyName: '会社名', clientNamePlaceholder: 'クライアント株式会社', address: '住所', addressPlaceholder: '東京都千代田区1-1...', yourDetails: 'あなたの詳細', yourCompanyNamePlaceholder: 'あなたの会社', yourAddressPlaceholder: 'あなたの住所456...', invoiceDetails: '請求書の詳細', invoiceNumber: '請求書番号', issueDate: '発行日', dueDate: '支払期日', currency: '通貨', invoiceItems: '請求書項目', description: '説明', qty: '数量', price: '価格', addItem: '+ 項目を追加', totalsAndNotes: '合計とメモ', discount: '割引', discountPlaceholder: '10% または 50', taxRate: '税率 (%)', paymentLink: '支払いリンク', paymentLinkPlaceholder: 'https://provider.com/pay', notes: 'メモ', notesPlaceholder: 'お取引ありがとうございます！', downloadPDF: 'PDFをダウンロード', print: '印刷', reset: 'リセット', from: 'から', to: 'へ', subtotal: '小計', tax: '税金', total: '合計', payNow: '今すぐ支払う', pdfBillTo: '請求先', pdfDateIssued: '発行日', pdfDueDate: '支払期日', pdfInvoice: '請求書', pdfDescription: '説明', pdfQuantity: '数量', pdfUnitPrice: '単価', pdfAmount: '金額', pdfSubtotal: '小計', pdfDiscount: '割引', pdfTax: '税金', pdfTotal: '合計', pdfNotes: 'メモ', pdfPayOnline: 'オンラインで支払う',
    }
};
